services:
  prometheus:
    build:
      context: ./prometheus
    container_name: prometheus
    environment:
      HF_TOKEN: ${HF_TOKEN}
    ports:
      - "9090:9090"

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
